package systemd

import (
	"bytes"
	"fmt"
	"text/template"
)

// Default templates. The .Description/.Name/.HolosBinary etc. vars are
// expanded via text/template; everything else is literal.
const unitTemplate = `# Generated by holos. Edit at your own risk.
# Run ` + "`holos install`" + ` again to regenerate.
[Unit]
Description=holos project {{.Project}}
Documentation=https://github.com/zeroecco/holos
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
{{- if .User}}
User={{.User}}
{{- end}}
ExecStart={{.HolosBinary}} up{{.StateFlag}} -f {{.ComposeFile}}
ExecStop={{.HolosBinary}} down{{.StateFlag}} {{.Project}}
TimeoutStartSec=300
Restart=no

[Install]
WantedBy={{.WantedBy}}
`

// Render returns the textual unit content plus the absolute path it
// should be written to. It does not touch the filesystem, so callers can
// preview, diff, or test the output in isolation. Validation here is
// strict: we'd rather refuse to render than emit a unit that will fail
// opaquely at boot.
func Render(spec UnitSpec) (path, content string, err error) {
	if err := spec.validate(); err != nil {
		return "", "", err
	}

	d := unitTemplateData{
		Project:     spec.Project,
		HolosBinary: spec.HolosBinary,
		ComposeFile: spec.ComposeFile,
		User:        spec.User,
	}
	d.StateFlag = renderStateFlag(spec.StateDir)
	switch spec.Scope {
	case ScopeUser:
		d.WantedBy = "default.target"
		// User scope doesn't honor User= and we don't want it there:
		// strip it defensively even if a caller set it.
		d.User = ""
	case ScopeSystem:
		d.WantedBy = "multi-user.target"
	}

	tmpl, err := template.New("unit").Parse(unitTemplate)
	if err != nil {
		return "", "", fmt.Errorf("parse unit template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		return "", "", fmt.Errorf("render unit: %w", err)
	}

	unitPath, err := UnitPath(spec.Scope, spec.Project)
	if err != nil {
		return "", "", err
	}
	return unitPath, buf.String(), nil
}

func renderStateFlag(stateDir string) string {
	if stateDir == "" {
		return ""
	}
	// Prefix with a space so it slots into ExecStart=... and
	// ExecStop=... naturally. The flag is rendered between the
	// subcommand and the positional project argument
	// (`holos down --state-dir /tmp/state demo`) because Go's flag package
	// stops parsing at the first non-flag arg; a trailing --state-dir would be
	// silently ignored and the unit would touch the default state path on stop.
	return " --state-dir " + stateDir
}

type unitTemplateData struct {
	Project     string
	HolosBinary string
	ComposeFile string
	StateFlag   string
	User        string
	WantedBy    string
}
