// Package systemd generates and installs systemd unit files that
// bring holos projects back up after a host reboot.
//
// Two installation scopes are supported:
//
//   - "user" (default): drops the unit under $XDG_CONFIG_HOME/systemd/user
//     so it runs as the invoking user, with no root required. This is
//     the right choice for personal workstations and mirrors what
//     `podman generate systemd --user` does.
//   - "system": drops the unit under /etc/systemd/system so the host
//     brings the project up even before anyone logs in. This requires
//     write access to that directory (i.e. sudo / root).
//
// The generated unit is intentionally minimal: Type=oneshot plus
// RemainAfterExit so systemctl reports the service as "active" while
// the VMs themselves stay daemonized under holos's own state tracking.
// ExecStart runs `holos up [--state-dir D] -f <abs compose>`,
// ExecStop runs `holos down [--state-dir D] <project>`; flags are
// always rendered before any positional argument because Go's flag
// parser stops at the first non-flag token, which would otherwise
// drop --state-dir on stop. This keeps stop/start semantics identical
// to what the operator would type at the CLI.
package systemd

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

// projectNamePattern mirrors compose.ValidateName; duplicated here so
// this package stays free of compose/config imports. UnitPath and
// Render call this defensively so that any caller slipping a bad
// project name past the CLI validator still cannot escape the unit
// directory (e.g. "foo/../../etc/passwd" landing in
// /etc/systemd/system/holos-foo/../../etc/passwd.service).
var projectNamePattern = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$`)

func validateProjectName(name string) error {
	if name == "" {
		return fmt.Errorf("project name is empty")
	}
	if !projectNamePattern.MatchString(name) {
		return fmt.Errorf("project %q must match %s", name, projectNamePattern.String())
	}
	return nil
}

// Scope selects between a per-user unit and a host-wide unit.
type Scope string

const (
	ScopeUser   Scope = "user"
	ScopeSystem Scope = "system"
)

// UnitSpec describes the unit we want to emit. All paths must be
// absolute: systemd does not expand $HOME or relative paths at boot.
type UnitSpec struct {
	// Project is the holos project name; used to compute the unit
	// filename (holos-<project>.service) and in log descriptions.
	Project string

	// ComposeFile is the absolute path to the holos.yaml the unit
	// should bring up at boot.
	ComposeFile string

	// HolosBinary is the absolute path to the holos executable.
	// We resolve this explicitly so the unit keeps working even if
	// the operator's PATH changes or the binary is moved. At boot,
	// systemd units run with an almost-empty PATH; a bare "holos"
	// would simply fail.
	HolosBinary string

	// StateDir, if non-empty, is passed as --state-dir to every
	// holos invocation in the unit. Useful for tests and for
	// non-standard deployments.
	StateDir string

	// Scope selects user vs system installation.
	Scope Scope

	// User, when set with ScopeSystem, is written as User= in the
	// unit so the VMs run under that account (and its cached state
	// directory) rather than root. Ignored for user scope.
	User string
}

// Default templates. The .Description/.Name/.HolosBinary etc. vars are
// expanded via text/template; everything else is literal.
const unitTemplate = `# Generated by holos. Edit at your own risk.
# Run ` + "`holos install`" + ` again to regenerate.
[Unit]
Description=holos project {{.Project}}
Documentation=https://github.com/zeroecco/holos
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
{{- if .User}}
User={{.User}}
{{- end}}
ExecStart={{.HolosBinary}} up{{.StateFlag}} -f {{.ComposeFile}}
ExecStop={{.HolosBinary}} down{{.StateFlag}} {{.Project}}
TimeoutStartSec=300
Restart=no

[Install]
WantedBy={{.WantedBy}}
`

// Render returns the textual unit content plus the absolute path it
// should be written to. It does not touch the filesystem, so callers can
// preview, diff, or test the output in isolation. Validation here is
// strict: we'd rather refuse to render than emit a unit that will fail
// opaquely at boot.
func Render(spec UnitSpec) (path, content string, err error) {
	if err := spec.validate(); err != nil {
		return "", "", err
	}

	type data struct {
		Project     string
		HolosBinary string
		ComposeFile string
		StateFlag   string
		User        string
		WantedBy    string
	}
	d := data{
		Project:     spec.Project,
		HolosBinary: spec.HolosBinary,
		ComposeFile: spec.ComposeFile,
		User:        spec.User,
	}
	if spec.StateDir != "" {
		// Prefix with a space so it slots into ExecStart=... and
		// ExecStop=... naturally. The flag is rendered between the
		// subcommand and the positional project argument
		// (`holos down --state-dir /tmp/state demo`) because Go's
		// flag package stops parsing at the first non-flag arg; a
		// trailing --state-dir would be silently ignored and the
		// unit would touch the default state path on stop.
		d.StateFlag = " --state-dir " + spec.StateDir
	}
	switch spec.Scope {
	case ScopeUser:
		d.WantedBy = "default.target"
		// User scope doesn't honor User= and we don't want it there:
		// strip it defensively even if a caller set it.
		d.User = ""
	case ScopeSystem:
		d.WantedBy = "multi-user.target"
	}

	tmpl, err := template.New("unit").Parse(unitTemplate)
	if err != nil {
		return "", "", fmt.Errorf("parse unit template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		return "", "", fmt.Errorf("render unit: %w", err)
	}

	unitPath, err := UnitPath(spec.Scope, spec.Project)
	if err != nil {
		return "", "", err
	}
	return unitPath, buf.String(), nil
}

// UnitPath returns where a unit for the given project/scope lives,
// without touching the filesystem. Callers can use this to present a
// dry-run path to the user before committing.
func UnitPath(scope Scope, project string) (string, error) {
	if err := validateProjectName(project); err != nil {
		return "", err
	}
	name := fmt.Sprintf("holos-%s.service", project)
	switch scope {
	case ScopeUser:
		dir, err := userUnitDir()
		if err != nil {
			return "", err
		}
		return filepath.Join(dir, name), nil
	case ScopeSystem:
		return filepath.Join("/etc/systemd/system", name), nil
	default:
		return "", fmt.Errorf("unknown scope %q", scope)
	}
}

// Install writes the unit to disk (creating parent dirs as needed)
// and, unless Dry is set on the returned Result, daemon-reload + enable
// it so the service survives reboot. Missing systemctl is tolerated
// for user scope (e.g. running in a minimal container); the unit file
// is still produced so the operator can install it by hand.
func Install(spec UnitSpec, enable bool) (Result, error) {
	path, content, err := Render(spec)
	if err != nil {
		return Result{}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return Result{}, fmt.Errorf("create unit dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return Result{}, fmt.Errorf("write unit: %w", err)
	}

	res := Result{UnitPath: path, Scope: spec.Scope}

	if _, lookErr := exec.LookPath("systemctl"); lookErr != nil {
		res.SystemctlMissing = true
		return res, nil
	}

	if err := systemctlReload(spec.Scope); err != nil {
		// A daemon-reload failure is non-fatal: the unit is on disk
		// and a subsequent manual reload will pick it up. We surface
		// the error on the Result so the CLI can warn.
		res.Warnings = append(res.Warnings, fmt.Sprintf("daemon-reload: %v", err))
	}

	if enable {
		if err := systemctlEnable(spec.Scope, path, true); err != nil {
			res.Warnings = append(res.Warnings, fmt.Sprintf("enable: %v", err))
		} else {
			res.Enabled = true
		}
	}
	return res, nil
}

// Uninstall disables the unit (best effort) and removes its file. A
// missing file is not an error; it makes the command idempotent.
func Uninstall(scope Scope, project string) (Result, error) {
	path, err := UnitPath(scope, project)
	if err != nil {
		return Result{}, err
	}
	res := Result{UnitPath: path, Scope: scope}

	if _, lookErr := exec.LookPath("systemctl"); lookErr == nil {
		if err := systemctlDisable(scope, path); err != nil {
			res.Warnings = append(res.Warnings, fmt.Sprintf("disable: %v", err))
		}
	} else {
		res.SystemctlMissing = true
	}

	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return res, fmt.Errorf("remove unit: %w", err)
	}

	if _, lookErr := exec.LookPath("systemctl"); lookErr == nil {
		_ = systemctlReload(scope)
	}
	return res, nil
}

// Result describes what Install/Uninstall did, for CLI reporting.
type Result struct {
	UnitPath         string
	Scope            Scope
	Enabled          bool
	SystemctlMissing bool
	Warnings         []string
}

// --- internals --------------------------------------------------------------

func (s UnitSpec) validate() error {
	// The DNS-label check already rejects whitespace, slashes, and
	// every other character that systemd treats specially, so it
	// subsumes the earlier "no slash or whitespace" rule.
	if err := validateProjectName(s.Project); err != nil {
		return err
	}
	if s.ComposeFile == "" {
		return errors.New("compose file path is required")
	}
	if !filepath.IsAbs(s.ComposeFile) {
		return fmt.Errorf("compose file must be absolute, got %q", s.ComposeFile)
	}
	if err := rejectUnsafePathChars("compose file", s.ComposeFile); err != nil {
		return err
	}
	if s.HolosBinary == "" {
		return errors.New("holos binary path is required")
	}
	if !filepath.IsAbs(s.HolosBinary) {
		return fmt.Errorf("holos binary must be absolute, got %q", s.HolosBinary)
	}
	if err := rejectUnsafePathChars("holos binary", s.HolosBinary); err != nil {
		return err
	}
	if s.StateDir != "" && !filepath.IsAbs(s.StateDir) {
		return fmt.Errorf("state dir must be absolute, got %q", s.StateDir)
	}
	if s.StateDir != "" {
		if err := rejectUnsafePathChars("state dir", s.StateDir); err != nil {
			return err
		}
	}
	switch s.Scope {
	case ScopeUser, ScopeSystem:
	default:
		return fmt.Errorf("unknown scope %q", s.Scope)
	}
	return nil
}

// unsafeExecChars are characters that change systemd's tokenisation
// of an ExecStart/ExecStop line or collide with systemd specifiers.
// systemd(5) parses Exec* with sh(1)-style quoting, expands %x
// specifiers, and treats ; as a conditional command separator. We
// could emit quotes and escape these, but getting that right across
// every systemd version is fragile; refusing to emit a unit with a
// path that would need escaping is a loud, survivable failure, and
// the caller can move the compose file / binary / state dir to a
// path without any of these characters. The set intentionally
// includes the whole whitespace family so a newline smuggled via
// an env var can't split a command across lines.
const unsafeExecChars = " \t\n\r\"'\\`$%;"

func rejectUnsafePathChars(field, value string) error {
	if i := strings.IndexAny(value, unsafeExecChars); i >= 0 {
		return fmt.Errorf(
			"%s %q contains character %q which would break systemd unit parsing; move to a path without whitespace or shell metacharacters",
			field, value, value[i:i+1])
	}
	return nil
}

func userUnitDir() (string, error) {
	// XDG_CONFIG_HOME is the systemd-documented location. If unset,
	// ~/.config/systemd/user is the conventional fallback.
	if cfg := os.Getenv("XDG_CONFIG_HOME"); cfg != "" {
		return filepath.Join(cfg, "systemd", "user"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home dir: %w", err)
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

func systemctlReload(scope Scope) error {
	args := scopeArgs(scope)
	args = append(args, "daemon-reload")
	return runSystemctl(args...)
}

func systemctlEnable(scope Scope, unitPath string, now bool) error {
	args := scopeArgs(scope)
	args = append(args, "enable")
	if now {
		args = append(args, "--now")
	}
	// Pass the absolute path so systemctl treats it as "link in place
	// and enable", which is friendlier than requiring the unit to be
	// in a search path first.
	args = append(args, unitPath)
	return runSystemctl(args...)
}

func systemctlDisable(scope Scope, unitPath string) error {
	args := scopeArgs(scope)
	args = append(args, "disable", "--now", filepath.Base(unitPath))
	return runSystemctl(args...)
}

func scopeArgs(scope Scope) []string {
	if scope == ScopeUser {
		return []string{"--user"}
	}
	return nil
}

func runSystemctl(args ...string) error {
	cmd := exec.Command("systemctl", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}
